services:
  apigateway:
    build: .
    container_name: apigateway
    ports:
      - "8000:8000"
    environment:
      AUTENTICACION_URL: http://auth_nginx
      REPORTES_URL: http://reportes
      CITAS_URL: http://spring_citas:8080
      HISTORIAL_URL: http://historialClinico:5000
      NOTIFICACIONES_URL: http://flask_service:5000
