services:
  apigateway:
    build: .
    container_name: apigateway
    ports:
      - "8000:8000"
    environment:
      AUTENTICACION_URL: http://auth_service:8000
      REPORTES_URL: http://reportes:9000
      CITAS_URL: http://citas:8080
      HISTORIAL_URL: http://historialClinico:5000
      NOTIFICACIONES_URL: http://flask_service:5001