services:
  db_citas:
    image: mysql:8.0
    container_name: db_citas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: citas_db
    ports:
      - "3307:3306"
    volumes:
      - citas_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  db_reportes:
    image: mysql:8.0
    container_name: db_reportes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reportes_db
    ports:
      - "3310:3306"
    volumes:
      - reportes_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  reportes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reportes
    working_dir: /var/www/html
    ports:
      - "8003:9000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db_reportes
      DB_PORT: 3306
      DB_DATABASE: reportes_db
      DB_USERNAME: root
      DB_PASSWORD: root
      CITAS_URL: "http://localhost:8080"
    depends_on:
      db_reportes:
        condition: service_healthy

volumes:
  citas_mysql_data:
  reportes_mysql_data:
