services:
  auth-service:
    build: .
    container_name: auth_service
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=auth_mysql
      - DB_PORT=3306
      - DB_DATABASE=auth_db
      - DB_USERNAME=root
      - DB_PASSWORD=12345
    depends_on:
      - auth_mysql

  auth_mysql:
    image: mysql:8
    container_name: auth_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=auth_db
    volumes:
      - auth_mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"

  nginx:
    image: nginx:latest
    container_name: auth_nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - auth-service

volumes:
  auth_mysql_data:
